FROM golang:1.22-bullseye AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" \
    -o server .

FROM gcr.io/distroless/static-debian12:latest
COPY --from=builder /src/server /server
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/server"]
