FROM python:3.10-alpine

RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev \
    python3-dev \
    # для numpy потрібні заголовки python3-dev, gfortran тощо
    gfortran \
    blas-dev \
    lapack-dev \
    bash

WORKDIR /app
COPY requirements/backend.in .
RUN pip install --no-cache-dir -r backend.in

COPY . .
EXPOSE 8000

CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8000"]
