FROM python:3.10-alpine

RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev \
    bash

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

CMD ["uvicorn", "spaceship.app:app", "--host", "0.0.0.0", "--port", "8000"]
