version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_pass
      POSTGRES_DB: example_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.distroless
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
