version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jdbc:postgresql://db:5432/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.distroless
    depends_on:
      - db
    restart: on-failure
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
