FROM gradle:8.4-jdk21 AS builder

WORKDIR /home/gradle/project
COPY --chown=gradle:gradle . .

RUN ./gradlew shadowJar --no-daemon


FROM gcr.io/distroless/java21-debian12

WORKDIR /app
COPY --from=builder /home/gradle/project/build/libs/ktor-restful-service-all.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/ktor-restful-service-all.jar"]
