FROM gradle:8.4-jdk21 AS builder

WORKDIR /home/gradle/project
COPY --chown=gradle:gradle . .

RUN gradle installDist --no-daemon


FROM gcr.io/distroless/java21-debian12

WORKDIR /app
COPY --from=builder /home/gradle/project/build/install/ktor-restful-service .

WORKDIR /app/bin
EXPOSE 8080

ENTRYPOINT ["./ktor-restful-service"]
